import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-background text-foreground p-4 flex align-middle justify-around sticky top-0 right-0 left-0 text-xl">
          <div>
            <a href="">LOGO</a>
          </div>
          <nav className="space-x-4">
            <a href="">Home</a>
            <a href="/about">about</a>
            <a href="/contact-us">contact us</a>
          </nav>
        </header>
        {children}
        <footer className="bg-footerBg text-footerFg flex justify-around text-center p-10">
          <div className="p-2 text-left w-lg space-y-1">
            <h2>Sample site</h2>
            <p>Company site</p>
            <br />
            <p>Find your way across the world</p>
            <div className="flex flex-row justify-items-end space-x-7">
              <div>
                <a href="https://instagram.com">
                  <Image src="Instagram_Glyph_Gradient.svg" alt="Icon of instagram" width={30} height={30}></Image>
                </a>
              </div>
              <div>Logo2</div>
              <div>Logo3</div>
              <div>Logo4</div>
              <div>Logo5</div>
            </div>
          </div>
          <div className="p-2">
            section1
          </div>
          <div className="p-2">
            section1
          </div>
        </footer>
      </body>
    </html>
  );
}
